%% 获取MFCC二维数据
function mel_rgb = get_pic_MEL(audiodata, fs)
% 以采样率fs返回音频输入的mel频谱图。 该函数将输入的列视为单独的通道。
melSpec = melSpectrogram(audiodata,fs,...
    'WindowLength',2048,...
    'OverlapLength',1024, ...
    'FFTLength',4096, ...
    'NumBands',64, ...
    'FrequencyRange',[1,8e3]);
% VGG19需要的图像尺寸
imgSize = [224, 224];
im = ind2rgb(im2uint8(mat2gray(log(melSpec))), jet(256));
mel_rgb = imresize(im, imgSize);
end